{
  "containerProperties": {
    "command": [
      "echo",
      "hello world"
    ],
    "image": "public.ecr.aws/amazonlinux/amazonlinux:latest",
    "resourceRequirements": [
      {
        "type": "VCPU",
        "value": "1"
      },
      {
        "type": "MEMORY",
        "value": "2048"
      }
    ],
    "repositoryCredentials": {},
    "secrets": [],
    "environment": [
      {
        "name": "AWS_S3_BUCKET_PATH",
        "value": "s3://amir-training-b70c6730/test-sample"
      }
    ],
    "linuxParameters": {
      "tmpfs": [],
      "devices": []
    },
    "mountPoints": [],
    "ulimits": [],
    "logConfiguration": {
      "options": {},
      "secretOptions": []
    },
    "volumes": []
  },
  "platformCapabilities": [
    "EC2"
  ],
  "type": "container",
  "retryStrategy": {
    "evaluateOnExit": []
  },
  "jobDefinitionName": "test-job-mx-21-jan-2025",
  "parameters": {}
}
