{
  "jobDefinitionName": "getting-started-ec2-job-definition-ammir",
  "containerProperties": {
    "command": [],
    "image": "public.ecr.aws/amazonlinux/amazonlinux:latest",
    "resourceRequirements": [
      {
        "type": "VCPU",
        "value": "1"
      },
      {
        "type": "MEMORY",
        "value": "2048"
      }
    ],
    "secrets": [],
    "environment": [],
    "linuxParameters": {
      "tmpfs": [],
      "devices": []
    },
    "ulimits": []
  },
  "platformCapabilities": [
    "EC2"
  ],
  "type": "container"
}
