# SPDX-FileCopyrightText: Copyright (c) University College London. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

## This file is used to configure pre-commit hooks
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
#
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
        exclude: 'data/.*|docs/.*'
        exclude_types: [markdown]
    -   id: end-of-file-fixer
        exclude: 'data/.*|docs/.*'
        exclude_types: [markdown]
    -   id: check-yaml
        exclude: '.github/workflows/.*|docs/aws-services/.*'
    -   id: check-added-large-files
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          [
           "--rcfile=tests/.pylintrc"
          ]
        exclude: 'data/.*|docs/.*' #|tests/.*'
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        exclude: 'src/amir/.*|tests/.*'
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
      - id: codespell
        name: codespell
        description: Checks for common misspellings in text files.
        entry: codespell
        language: python
        types: [ text ]
        exclude: 'data/.*|docs/.*|tutorials/automatic-medical-image-reporting/src/amir/.*|tutorials/automatic-medical-image-reporting/amir.svg|tutorials/README.md'
